name: whisky_app
description: Whisky guidbook app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.1.0+1
  firebase_core: ^0.4.0+9
  firebase_database: ^3.0.7
  shared_preferences: ^0.5.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: false

  assets:
    - assets/images/whisky.jpg
    - assets/images/book.jpg